from __future__ import annotations
import os, sys
from pathlib import Path
import numpy as np

_HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(_HERE))
from m3_runner import make_problem, _student_Cs, _relu, _relu_p   # type: ignore

CKPT_DIR = _HERE / "unified_v3d"
OUT_DIR = _HERE / "tables"
OUT_DIR.mkdir(exist_ok=True)


def polar(g: np.ndarray) -> np.ndarray:
    U, _, Vh = np.linalg.svd(g, full_matrices=False)
    return U @ Vh


def fresh_grad(W: np.ndarray, X: np.ndarray, y: np.ndarray, a_s: np.ndarray) -> np.ndarray:
    n = X.shape[0]
    z = X @ W; h = _relu(z); f = h @ a_s; err = f - y
    dphi = _relu_p(z); tmp = err[:, None] * dphi * a_s[None, :]
    return (2.0 / n) * (X.T @ tmp)


def compute(p: int, r_t: int, r_s: int, eta: float, ckpt_path: Path,
            n: int = 15000, seed: int = 5, teacher_act: str = 'relu') -> dict:
    z = np.load(ckpt_path, allow_pickle=True)
    W = z['W']
    X, y, _, _, U_t, a_t = make_problem(p, r_t, n, n_test=2000,
                                        seed=seed, teacher_act=teacher_act)
    a_s = np.ones(r_s)            # student head matches the runner default

    # --- Polar Frobenius split (Theorem ``thm:split''):
    g = fresh_grad(W, X, y, a_s)
    P = polar(g)
    P_V = U_t @ U_t.T
    Pv = P_V @ P
    Pp = P - Pv
    polar_V = float(np.sum(Pv * Pv))
    polar_perp = float(np.sum(Pp * Pp))
    polar_M = float(np.sum(P * P))

    # --- Plateau height vs head-fit oracle (Claim ``claim:plateau''):
    L = z['L_full']
    L_plateau = float(np.mean(L[int(0.7 * len(L)):]))
    L_V_opt = float(z['L_V_opt_train'][-1]) if 'L_V_opt_train' in z.files else float('nan')
    L_AGOP_opt = float(z['L_AGOP_opt_train'][-1]) if 'L_AGOP_opt_train' in z.files else float('nan')
    ratio = L_plateau / max(L_V_opt, 1e-12)

    # --- Direction-only AGOP alignment metrics (Test F):
    Cs = _student_Cs(X, W, a_s)
    G_s = W @ Cs @ W.T; G_s = 0.5 * (G_s + G_s.T)
    lam, V_eig = np.linalg.eigh(G_s); lam = lam[::-1]; V_eig = V_eig[:, ::-1]
    lam_clipped = np.clip(lam, 0, None)
    s_lam = float(lam_clipped.sum())
    in_V_per = np.einsum("ji,jk,ki->i", V_eig, P_V, V_eig)
    mass_in_V = float(np.sum(lam_clipped * in_V_per) / max(s_lam, 1e-30))
    V_top = V_eig[:, :r_t]
    QA, _ = np.linalg.qr(V_top); QB, _ = np.linalg.qr(U_t)
    cos_per = np.clip(np.linalg.svd(QA.T @ QB, compute_uv=False), 0.0, 1.0)
    cos2_min = float(cos_per[-1] ** 2)
    cos2_mean = float((cos_per ** 2).mean())
    PVW = U_t.T @ W
    A_sub = float(np.sum(PVW * PVW)) / float(np.sum(W * W))

    # --- Drift rate scaling (Claim ``claim:drift''):
    M = min(p, r_s)
    rate_pred = eta * r_t / M
    cos2_seq = np.asarray(z['cos2_min_AGOP'], dtype=float)
    steps = np.asarray(z['step'], dtype=float)
    half = len(cos2_seq) // 2
    rate_meas_per_step = (cos2_seq[-1] - cos2_seq[half]) / max(steps[-1] - steps[half], 1.0)

    return dict(
        p=p, r_t=r_t, r_s=r_s, eta=eta,
        polar_V=polar_V, polar_perp=polar_perp, polar_M=polar_M,
        L_plateau=L_plateau, L_V_opt=L_V_opt, L_AGOP_opt=L_AGOP_opt, ratio=ratio,
        cos2_min=cos2_min, cos2_mean=cos2_mean, mass_V=mass_in_V, A_sub=A_sub,
        rate_pred=rate_pred, rate_meas=rate_meas_per_step,
    )


# ------------------------------------------------------------------
# Configurations to populate each table. (panel-letter-style labels are
# kept for traceability with ``run_14configs.py``.)
# ------------------------------------------------------------------
RELU_CKPT = lambda p, rt, rs, eta: (
    CKPT_DIR / f"Muon_p{p}_rt{rt}_rs{rs}_eta{eta}_p{p}_rt{rt}_rs{rs}_n15000_seed5.npz"
)

POLAR_ROWS = [(100, 4, 50, 2.0), (100, 8, 50, 1.5), (100, 12, 50, 1.5)]
PLATEAU_ROWS = [(100, 8, 50, 1.0), (100, 8, 50, 1.5),
                (100, 12, 50, 1.5)]
DRIFT_ROWS = [(100, 6, 50, 1.5), (100, 8, 50, 1.5),
              (100, 10, 50, 1.5), (100, 12, 50, 1.5)]
NFA_ROWS = [(100, 6, 50, 1.5), (100, 8, 50, 1.5),
            (100, 10, 50, 1.5), (100, 12, 50, 1.5)]


def _row_or_skip(p, rt, rs, eta):
    fp = RELU_CKPT(p, rt, rs, eta)
    if not fp.exists():
        print(f"  [skip] missing checkpoint {fp.name}")
        return None
    return compute(p, rt, rs, eta, fp)


def emit(path: Path, lines: list[str]):
    path.write_text("\n".join(lines) + "\n")
    print(f"  wrote {path.relative_to(_HERE.parent)}  ({path.stat().st_size} B)")


def make_polar_table():
    lines = [
        r"% Auto-generated by code/make_appendix_tables.py -- do not edit by hand.",
        r"\begin{tabular}{lrrrrrr}",
        r"\toprule",
        r"Config $(\sigma_t,r_t,r_s)$ & predicted $V$ & measured $V$"
        r" & predicted $\perp$ & measured $\perp$ & predicted $M$ & measured $M$ \\",
        r"\midrule",
    ]
    for p, rt, rs, eta in POLAR_ROWS:
        r = _row_or_skip(p, rt, rs, eta)
        if r is None: continue
        M = min(p, rs)
        lines.append(
            f"ReLU, $r_t={rt}$, $r_s={rs}$ & {rt} & {r['polar_V']:.2f} & "
            f"{M-rt} & {r['polar_perp']:.2f} & {M} & {r['polar_M']:.2f} \\\\"
        )
    lines += [r"\bottomrule", r"\end{tabular}"]
    emit(OUT_DIR / "tab_polar_mass.tex", lines)


def make_plateau_table():
    lines = [
        r"% Auto-generated by code/make_appendix_tables.py -- do not edit by hand.",
        r"\begin{tabular}{lrrr}",
        r"\toprule",
        r"$(\sigma_t, p, r_t, r_s, \eta)$ & $L_{\mathrm{plateau}}$"
        r" & $L_{V,\mathrm{opt}}$ & ratio $L_{\mathrm{plateau}} / L_{V,\mathrm{opt}}$ \\",
        r"\midrule",
    ]
    for p, rt, rs, eta in PLATEAU_ROWS:
        r = _row_or_skip(p, rt, rs, eta)
        if r is None: continue
        lines.append(
            f"ReLU, $({p}, {rt}, {rs}, {eta})$ & {r['L_plateau']:.2f} & "
            f"{r['L_V_opt']:.2f} & {r['ratio']:.1f} \\\\"
        )
    lines += [r"\bottomrule", r"\end{tabular}"]
    emit(OUT_DIR / "tab_plateau_height.tex", lines)


def make_drift_table():
    lines = [
        r"% Auto-generated by code/make_appendix_tables.py -- do not edit by hand.",
        r"\begin{tabular}{lrrr}",
        r"\toprule",
        r"$(\sigma_t, p, r_t, r_s, \eta)$"
        r" & predicted $\eta r_t/M$ & measured $d\!\cos^2_{\min}/dt$ & ratio \\",
        r"\midrule",
    ]
    for p, rt, rs, eta in DRIFT_ROWS:
        r = _row_or_skip(p, rt, rs, eta)
        if r is None: continue
        rp = r['rate_pred']; rm = r['rate_meas']
        ratio = rm / rp if rp != 0 else float('nan')
        lines.append(
            f"ReLU, $({p}, {rt}, {rs}, {eta})$ & "
            f"${rp:.2f}$ & ${rm:.1e}$ & ${ratio:+.2e}$ \\\\"
        )
    lines += [r"\bottomrule", r"\end{tabular}"]
    emit(OUT_DIR / "tab_drift.tex", lines)


def make_nfa_table():
    lines = [
        r"% Auto-generated by code/make_appendix_tables.py -- do not edit by hand.",
        r"\begin{tabular}{lccc}",
        r"\toprule",
        r"$(\sigma_t, p, r_t, r_s, \eta)$"
        r" & $\overline{\cos^2}$ & $\mathrm{mass}_V(G_s)$ & $A_{\mathrm{sub}}$ \\",
        r"\midrule",
    ]
    for p, rt, rs, eta in NFA_ROWS:
        r = _row_or_skip(p, rt, rs, eta)
        if r is None: continue
        lines.append(
            f"ReLU, $({p}, {rt}, {rs}, {eta})$ & {r['cos2_mean']:.2f}"
            f" & {r['mass_V']:.2f} & {r['A_sub']:.2f} \\\\"
        )
    lines += [r"\bottomrule", r"\end{tabular}"]
    emit(OUT_DIR / "tab_nfa.tex", lines)


def main():
    print(f"Reading checkpoints from {CKPT_DIR}")
    print(f"Writing tables to       {OUT_DIR}")
    make_polar_table()
    make_plateau_table()
    make_drift_table()
    make_nfa_table()


if __name__ == "__main__":
    main()
